export const WORDS_REQUEST = 'WORDS/WORDS_REQUEST';
export const WORDS_REQUEST_SUCCESS = 'WORDS/WORDS_REQUEST_SUCCESS';
export const WORDS_REQUEST_SIMILAR = 'WORDS/WORDS_REQUEST_SIMILAR';
export const WORDS_REQUEST_FAILURE = 'WORDS/WORDS_REQUEST_FAILURE';

export const FAVORITE_WORDS_ADD = 'FAVORITE_WORDS/FAVORITE_WORDS_ADD';
export const FAVORITE_WORDS_REMOVE = 'FAVORITE_WORDS/FAVORITE_WORDS_REMOVE';
export const FAVORITE_WORDS_PHRASE_FILTER = 'FAVORITE_WORDS/FAVORITE_WORDS_PHRASE_FILTER';
export const FAVORITE_WORDS_PART_OF_SPEECH_FILTER_ADD = 'FAVORITE_WORDS/FAVORITE_WORDS_PART_OF_SPEECH_FILTER_ADD';
export const FAVORITE_WORDS_PART_OF_SPEECH_FILTER_REMOVE = 'FAVORITE_WORDS/FAVORITE_WORDS_PART_OF_SPEECH_FILTER_REMOVE';
export const FAVORITE_WORDS_MOVE_TO = 'FAVORITE_WORDS/FAVORITE_WORDS_MOVE_TO';
